FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY syslog-inspector.go .
RUN go build -o syslog-inspector syslog-inspector.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /app/syslog-inspector .
CMD ["./syslog-inspector"]