services:
  # Syslog encryptor creates socket on host
  syslog-encryptor:
    build: .
    container_name: syslog-encryptor
    env_file: .env
    environment:
      SOCKET_PATH: "/syslog/syslog.sock"
    volumes:
      - empty_dir:/syslog
    restart: unless-stopped

  # MariaDB mounts the socket file directly as /dev/log
  mariadb:
    image: mariadb:11.0
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-config.cnf:/etc/mysql/conf.d/audit.cnf
      - empty_dir:/syslog
    ports:
      - "3306:3306"
    command: ["sh", "-c", "while [ ! -S /syslog/syslog.sock ]; do echo 'Waiting for syslog socket...' && sleep 1; done && echo 'Socket available, starting MariaDB...' && ln -s /syslog/syslog.sock /dev/log && docker-entrypoint.sh mariadbd"]
    restart: unless-stopped

volumes:
  mariadb_data: {}
  empty_dir: {}
