services:
  # Syslog encryptor creates socket on host
  syslog-encryptor:
    build: .
    container_name: syslog-encryptor
    env_file: .env
    environment:
      SOCKET_PATH: "/tmp/syslog.sock"
    volumes:
      # Create socket on host filesystem
      - /tmp:/tmp
    restart: unless-stopped

  # MariaDB mounts the socket file directly as /dev/log
  mariadb:
    image: mariadb:11.0
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-config.cnf:/etc/mysql/conf.d/audit.cnf
      # Bind mount the socket file directly to /dev/log
      - /tmp/syslog.sock:/dev/log
    ports:
      - "3306:3306"
    depends_on:
      - syslog-encryptor
    command: ["sh", "-c", "while [ ! -S /dev/log ]; do echo 'Waiting for /dev/log socket...' && sleep 1; done && echo 'Socket available, starting MariaDB...' && docker-entrypoint.sh mariadbd"]
    restart: unless-stopped

volumes:
  mariadb_data: